version: '3.9'
services:
  mongodb:
    image: "mongo"
    container_name: mongodb
    volumes:
      - data-mongo:/data/db
      
    #! set env file
    #env_file:
     # - ./env/mongo.env

    #!set env
    #environment:
    #  - USERNAME=root 

    #!set network
    #networks:
    #  - app-net  
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    container_name: backend-express  
   #! you add build by address name file and args 
   # build: 
   #   context: ./backend
   #   dockerfile: dockerfile-dev
    #  args:
    #    - arg1=value1
     
  frontend:
    build: ./frontend
    container_name: frontend-react
    ports:
      - "3000:3000"
    depends_on:
      - backend 
    stdin_open: true
    tty: true   

volumes:
  data-mongo:

#! you add network to docker compose
#networks:
#  app-net: